apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNPostgreSQL
metadata:
  name: my-vaultwarden-postgres
  namespace: my-vaultwarden
spec:
  parameters:
    instances: 1
    service:
      majorVersion: "15"
      serviceLevel: besteffort
      repackEnabled: true
    backup:
      schedule: "* * * * *"
      deletionProtection: true
    updateStrategy:
      type: Immediate
  writeConnectionSecretToRef:
    name: postgres-creds
