apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    chart: vaultwarden
    repoURL: https://guerzon.github.io/vaultwarden
    targetRevision: 0.22.7
    helm:
      releaseName: my-vaultwarden
      valuesObject:
        domain: https://warden.contoso.com:8443
        database:
          type: postgresql
          existingSecret: postgres-creds-r
          existingSecretKey: POSTGRESQL_URL
  destination:
    server: "https://kubernetes.default.svc"
    namespace: my-vaultwarden
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy